// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0zSRERJL7C7ovhxf7fEoZzmIWbAP_-WI',
    appId: '1:1049046216859:web:50a2e70487dcc79107d63e',
    messagingSenderId: '1049046216859',
    projectId: 'fireship-quizapp-e2bc5',
    authDomain: 'fireship-quizapp-e2bc5.firebaseapp.com',
    storageBucket: 'fireship-quizapp-e2bc5.appspot.com',
    measurementId: 'G-154Y6L396C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6d1j47WbGetz530HhzVT6UhFK4pKJN6c',
    appId: '1:1049046216859:android:707fb369a1b73ad607d63e',
    messagingSenderId: '1049046216859',
    projectId: 'fireship-quizapp-e2bc5',
    storageBucket: 'fireship-quizapp-e2bc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt-sb0Og-55FNl3vD5nID16O6I11E0lcc',
    appId: '1:1049046216859:ios:36f4fdb9621d30b807d63e',
    messagingSenderId: '1049046216859',
    projectId: 'fireship-quizapp-e2bc5',
    storageBucket: 'fireship-quizapp-e2bc5.appspot.com',
    iosClientId: '1049046216859-sokn3ckqcagnjfj9dj2heeog01sjsbrc.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt-sb0Og-55FNl3vD5nID16O6I11E0lcc',
    appId: '1:1049046216859:ios:36f4fdb9621d30b807d63e',
    messagingSenderId: '1049046216859',
    projectId: 'fireship-quizapp-e2bc5',
    storageBucket: 'fireship-quizapp-e2bc5.appspot.com',
    iosClientId: '1049046216859-sokn3ckqcagnjfj9dj2heeog01sjsbrc.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );
}
